services:
  fika-server:
    image: ghcr.io/zhliau/fika-spt-server-docker:latest
    ports:
      - 6969:6969
    environment:
      # Provide the uid/gid of the user, or it will default to 0 (root)
      - UID=1000
      - GID=1000
      # If you want to auto-install Fika on an existing Fika-less SPT Server install, set this to true.
      # Will do nothing if your serverfiles mount already has a fika-server dir in user/mods/
      - INSTALL_FIKA=true
      # If you want the container to update SPT automatically if it detects the SPT server version does not match expected version, set this to true
      - AUTO_UPDATE_SPT=true
      # If you want the container to update Fika automatically if it detects the Fika server version does not match expected version, set this to true
      - AUTO_UPDATE_FIKA=true
      # If you don't want the container to change the file ownership of your server files, set this to false
      - TAKE_OWNERSHIP=true
    volumes:
      # Set this to the directory on your host containing either your existing SPT server files or where you wish to store a new SPT server install
      - ./path/to/server/files:/opt/server
